// Generated by gencpp from file traffic_sign_recognition/sign.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_RECOGNITION_MESSAGE_SIGN_H
#define TRAFFIC_SIGN_RECOGNITION_MESSAGE_SIGN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traffic_sign_recognition
{
template <class ContainerAllocator>
struct sign_
{
  typedef sign_<ContainerAllocator> Type;

  sign_()
    : sign_type(0.0)
    , area(0.0)  {
    }
  sign_(const ContainerAllocator& _alloc)
    : sign_type(0.0)
    , area(0.0)  {
  (void)_alloc;
    }



   typedef float _sign_type_type;
  _sign_type_type sign_type;

   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::traffic_sign_recognition::sign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_sign_recognition::sign_<ContainerAllocator> const> ConstPtr;

}; // struct sign_

typedef ::traffic_sign_recognition::sign_<std::allocator<void> > sign;

typedef boost::shared_ptr< ::traffic_sign_recognition::sign > signPtr;
typedef boost::shared_ptr< ::traffic_sign_recognition::sign const> signConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_sign_recognition::sign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_sign_recognition::sign_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traffic_sign_recognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'traffic_sign_recognition': ['/home/jorge/catkin_ws/src/traffic_sign_recognition/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign_recognition::sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_sign_recognition::sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign_recognition::sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_sign_recognition::sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign_recognition::sign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_sign_recognition::sign_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_sign_recognition::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80d74564147e7ccb5048d7289eea8101";
  }

  static const char* value(const ::traffic_sign_recognition::sign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80d74564147e7ccbULL;
  static const uint64_t static_value2 = 0x5048d7289eea8101ULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_sign_recognition::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_sign_recognition/sign";
  }

  static const char* value(const ::traffic_sign_recognition::sign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_sign_recognition::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sign_type\n\
float64 area\n\
";
  }

  static const char* value(const ::traffic_sign_recognition::sign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_sign_recognition::sign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sign_type);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_sign_recognition::sign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_sign_recognition::sign_<ContainerAllocator>& v)
  {
    s << indent << "sign_type: ";
    Printer<float>::stream(s, indent + "  ", v.sign_type);
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_SIGN_RECOGNITION_MESSAGE_SIGN_H
